const sidebarsWeb = {
  brandSidebars: [
    {
      type: "autogenerated",
      dirName: ".", // This must remain `.` if your new docs instance is in the base directory
    },
  ],
};

export default sidebarsWeb;
